#!/usr/bin/env python
import argparse
import json
import logging
import sys
from datadog import initialize, api

from datadog_creds import options

program_name = "get-timeboard"


if __name__ == '__main__':
    logging.basicConfig(level=logging.ERROR)
    parser = argparse.ArgumentParser(prog=program_name)
    parser.add_argument(
        "-t", "--title", type=str,
        help="title of timeboard to get",
        required=True,
    )
    args = parser.parse_args()

    initialize(**options)

    timeboards = api.Timeboard.get_all()
    for timeboard in timeboards['dashes']:
        logging.debug(json.dumps(timeboard))
        if timeboard['title'] == args.title:
            timeboard_id = timeboard['id']
            logging.debug("Found '%s' with id '%s'", args.title, timeboard_id)
            break
    else:
        logging.error("could not find timeboard '%s'", args.title)
        sys.exit(1)
    board = api.Timeboard.get(timeboard_id)
    print json.dumps(board, indent=4, separators=(',', ': '))
