#!/usr/bin/env python
import argparse
import json
import logging
from datadog import initialize, api

from datadog_creds import options

program_name = "put-timeboard"


if __name__ == '__main__':
    logging.basicConfig(level=logging.ERROR)
    parser = argparse.ArgumentParser(prog=program_name)
    parser.add_argument(
        "-f", "--filename", type=str,
        help="filename of previously exported timeboard",
        required=True,
    )
    args = parser.parse_args()

    initialize(**options)

    with open(args.filename, 'r') as f:
        board = json.load(f)

    board = api.Timeboard.update(
        board['dash']['id'],
        title=board['dash']['title'],
        description=board['dash']['description'],
        graphs=board['dash']['graphs'],
        template_variables=board['dash']['template_variables'],
    )
